In [4]:
import numpy as np
vector = np.array([10,20,30])
matrix = np.array([[5,10,15],[20,25,30],[35,40,45]])
print('Vector', vector)
print(matrix)
print(vector.shape)
print(matrix.shape)

Vector [10 20 30]
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
(3,)
(3, 3)


In [101]:
world_alcohol = np.genfromtxt('world_alcohol.csv', delimiter = ',', dtype= 'U75', skip_header=1)
#print(type(world_alcohol))
print(world_alcohol)
#print(world_alcohol.dtype)
ivory_1985 = world_alcohol[2, 4]
second_country = world_alcohol[1,2]
#print(ivory_1985)
#print(second_country)
countries = world_alcohol[:,2]
#print(countries)
alcohol_comsuption = world_alcohol[:,4]  
#print(alcohol_comsuption)
first_two_columns = world_alcohol[:, 0:2]
first_ten_years = world_alcohol[0:10, 0]
first_ten_rows = world_alcohol[0:10, :]
first_twenty_regions = world_alcohol[0:20, 1:3]
#print(first_two_columns)
#print('####')
#print(first_ten_years)
#print('####')
#print(first_ten_rows)
#print('####')
#print(first_twenty_regions)

[['1986' 'Western Pacific' 'Viet Nam' 'Wine' '0']
 ['1986' 'Americas' 'Uruguay' 'Other' '0.5']
 ['1985' 'Africa' "Cte d'Ivoire" 'Wine' '1.62']
 ...
 ['1986' 'Europe' 'Switzerland' 'Spirits' '2.54']
 ['1987' 'Western Pacific' 'Papua New Guinea' 'Other' '0']
 ['1986' 'Africa' 'Swaziland' 'Other' '5.15']]


In [82]:
countries_canada = (world_alcohol[:,2] == 'Canada')
#years_is_1984 = (world_alcohol[:,0] == '1984')
#print(countries_canada)
#print(years_1984)
country_algeria = world_alcohol[world_alcohol[:,2] == 'Algeria']
#print(country_algeria)
years_1984 = country_algeria[country_algeria[:,0] == '1984']
#print(years_1984)
is_algeria_1984 = (world_alcohol[:,0] == '1984') & (world_alcohol[:,2] == 'Algeria')
rows_with_algeria_1984 = world_alcohol[is_algeria_1984]
print(rows_with_algeria_1984)

[['1984' 'Africa' 'Algeria' 'Spirits' '0.01']
 ['1984' 'Africa' 'Algeria' 'Other' '0']
 ['1984' 'Africa' 'Algeria' 'Wine' '0.12']
 ['1984' 'Africa' 'Algeria' 'Beer' '0.2']]


In [120]:
world_alcohol_2 = world_alcohol.copy()

world_alcohol_2[:,0][world_alcohol_2[:,0] == '1986'] = '2018'
world_alcohol_2[:,3][world_alcohol_2[:,3] == 'Wine'] = 'Beer'
world_alcohol_2[:,4][world_alcohol_2[:,4] == ''] = '0'

alcohol_comsuption = world_alcohol_2[:,4].astype(float)
print('Total Alcohol :',alcohol_comsuption.sum())
print('Average comsuption :',alcohol_comsuption.mean())
#print(world_alcohol_2)
#print(alcohol_comsuption.dtype)

Total Alcohol : 3908.96
Average comsuption : 1.2001719373656738


In [134]:
selector = (world_alcohol[:, 0] == '1984') & (world_alcohol[:,2] == 'Canada')
canada_1984 = world_alcohol[selector]
canada_1984[:,4][canada_1984[:,4] == ''] = '0'
canada_drinking = canada_1984[:,4].astype(float).sum()
print(canada_drinking)
print(canada_1984)

9.59
[['1984' 'Americas' 'Canada' 'Spirits' '3.35']
 ['1984' 'Americas' 'Canada' 'Beer' '5']
 ['1984' 'Americas' 'Canada' 'Wine' '1.24']
 ['1984' 'Americas' 'Canada' 'Other' '0']]


In [182]:
totals = {}
countries =  world_alcohol[:,2] 
years = world_alcohol[world_alcohol[:,0] == '1989']
for country in countries:
    country_consumption = years[years[:,2]==country]
    country_consumption[:,4][country_consumption[:,4] == ''] = '0'
    alcohol_comsuption = country_consumption[:,4].astype(float)
    totals[country] = alcohol_comsuption.sum()

highest_values = 0
for country in totals:
    consumption = totals[country]
    if highest_values < consumption : 
        highest_values = consumption
        highest_key = country
    else:
        pass
        
print(highest_values)
print(highest_key)

16.29
Hungary
